seed: 42

heart:
  target: target
  numeric: [age, trestbps, chol, thalach, oldpeak, ca]
  categorical: [sex, cp, fbs, restecg, exang, slope, thal]
  models:
    logreg: {}
    rf: {n_estimators: 200, max_depth: null, class_weight: balanced}

stroke:
  target: stroke
  numeric: [age, avg_glucose_level, bmi]
  categorical: [gender, hypertension, heart_disease, ever_married, work_type, Residence_type, smoking_status]
  models:
    logreg: {}
    rf: {n_estimators: 300, max_depth: null, class_weight: balanced}

diabetes:
  target: Outcome
  numeric: [Pregnancies, Glucose, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age]
  categorical: []
  models:
    logreg: {}
    rf: {n_estimators: 200, max_depth: null, class_weight: balanced}
